site_name: Documentación del Proyecto Big Data
site_url: https://juanesmedcol.github.io/bigdata-infrastructure/
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  icon:
    logo: material/analytics
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Cambiar a modo oscuro

    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.math
    - content.mermaid
    - content.code.copy
    - content.code.highlight

nav:
  - Inicio: index.md
  - Ingesta de Datos: ingesta.md
  - Limpieza de Datos: limpieza.md

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.tabbed
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - glightbox
