site_name: Documentación del Proyecto Big Data
site_url: https://juanesmedcol.github.io/bigdata-infrastructure/
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.math
    - content.mermaid
    - content.code.copy
    - content.code.highlight

nav:
  - Inicio: index.md
  - Ingesta de Datos: ingesta.md
  - Limpieza de Datos: limpieza.md
  - Test Mermaid: mermaid-test.md

markdown_extensions:
  - tables
  - pymdownx.tabbed
  - pymdownx.superfences: 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji
  - attr_list
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
  - glightbox
