site_name: Documentación del Proyecto Big Data
theme:
  name: material
site_url: https://juanesmedcol.github.io/bigdata-infrastructure/
docs_dir: docs
use_directory_urls: false
nav:
  - Inicio: index.md
  - Ingesta de Datos: ingesta.md
  - Limpieza de Datos: limpieza.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2

