site_name: Documentación del Proyecto Big Data
site_url: https://juanesmedcol.github.io/bigdata-infrastructure/
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  palette:
    primary: green
    accent: light green
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.code.highlight
    - content.math
    - content.mermaid

nav:
  - Inicio: index.md
  - Ingesta de Datos: ingesta.md
  - Limpieza de Datos: limpieza.md
  - Test Mermaid: mermaid-test.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mermaid2
