name: Ingestión, Limpieza y Documentación

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora

jobs:
  ingest_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests pandas openpyxl

      - name: Run ingestion script
        run: python src/ingestion.py

      - name: Upload ingestion results
        uses: actions/upload-artifact@v4
        with:
          name: ingestion-results
          path: |
            src/static/auditoria/ingestion_report.txt
            src/static/db/ingestion.db
            src/static/csv/ingestion.csv
            src/static/xlsx/ingestion.xlsx

  clean_data:
    needs: ingest_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas openpyxl

      - name: Download ingestion results
        uses: actions/download-artifact@v4
        with:
          name: ingestion-results
          path: src/static/

      - name: Run cleaning script
        run: python src/cleaning.py

      - name: Upload cleaning results
        uses: actions/upload-artifact@v4
        with:
          name: cleaning-results
          path: |
            src/static/auditoria/cleaning_report.txt
            src/static/xlsx/cleaning.xlsx

  build_docs:
    needs: clean_data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs and theme
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Copiar archivos generados a docs/resultados
        run: |
          mkdir -p docs/resultados
          cp src/static/auditoria/*.txt docs/resultados/
          cp src/static/csv/*.csv docs/resultados/
          cp src/static/xlsx/*.xlsx docs/resultados/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site

